import type { ResumeLayout } from "@/shared/layoutSchema";
import { A4_PAGE, FONT_FAMILY } from "@/shared/layoutSchema";

export const exampleResumeLayout: ResumeLayout = {
  page: A4_PAGE,
  elements: [
    {
      type: "text",
      id: "full-name",
      pageIndex: 0,
      x: 50,
      y: 56,
      width: 330,
      fontSize: 28,
      fontFamily: FONT_FAMILY,
      fontWeight: "bold",
      lineHeight: 1.1,
      letterSpacing: 0,
      color: "#0f172a",
      content: "John Doe",
    },
    {
      type: "text",
      id: "headline",
      pageIndex: 0,
      x: 50,
      y: 96,
      width: 500,
      fontSize: 12,
      fontFamily: FONT_FAMILY,
      fontWeight: "normal",
      lineHeight: 1.4,
      letterSpacing: 0,
      color: "#334155",
      content: "Senior Full-Stack Engineer | john.doe@email.com | +1 555 0148 | New York, NY",
    },
    {
      type: "line",
      id: "divider-1",
      pageIndex: 0,
      x: 50,
      y: 126,
      width: 495,
      strokeWidth: 1,
      color: "#d1d5db",
    },
    {
      type: "text",
      id: "summary-title",
      pageIndex: 0,
      x: 50,
      y: 142,
      width: 160,
      fontSize: 11,
      fontFamily: FONT_FAMILY,
      fontWeight: "bold",
      lineHeight: 1.1,
      letterSpacing: 0,
      color: "#111827",
      content: "PROFESSIONAL SUMMARY",
    },
    {
      type: "text",
      id: "summary-copy",
      pageIndex: 0,
      x: 50,
      y: 164,
      width: 495,
      fontSize: 11,
      fontFamily: FONT_FAMILY,
      fontWeight: "normal",
      lineHeight: 1.45,
      letterSpacing: 0,
      color: "#1f2937",
      content:
        "Product-minded engineer with 8+ years building web applications and design systems. Expert in TypeScript, React, and backend API architecture, with a strong focus on quality, performance, and measurable business impact.",
    },
  ],
};
